resolver: lts-16.16
packages:
- squeal-postgresql
- squeal-postgresql-ltree
- squeal-postgresql-uuid-ossp
extra-deps:
- symbols-0.3.0.0@sha256:5d051bccbd4bcb33fa8ce076bd3cd2bacc90973682f7340976758947eaa128a9,964
